/**
 * microservice-company — AI agent control plane for autonomous company operations
 */

export {
  createOrg,
  getOrg,
  updateOrg,
  type Organization,
  type CreateOrgInput,
  type UpdateOrgInput,
  createTeam,
  getTeam,
  listTeams,
  updateTeam,
  deleteTeam,
  getTeamTree,
  getTeamMembers,
  type Team,
  type TeamTreeNode,
  type CreateTeamInput,
  type UpdateTeamInput,
  type ListTeamsOptions,
  addMember,
  getMember,
  listMembers,
  updateMember,
  removeMember,
  getMembersByRole,
  getMembersByTeam,
  type Member,
  type AddMemberInput,
  type UpdateMemberInput,
  type ListMembersOptions,
  createCustomer,
  getCustomer,
  listCustomers,
  updateCustomer,
  deleteCustomer,
  searchCustomers,
  mergeCustomers,
  getCustomerByEmail,
  type Customer,
  type CreateCustomerInput,
  type UpdateCustomerInput,
  type ListCustomersOptions,
  createVendor,
  getVendor,
  listVendors,
  updateVendor,
  deleteVendor,
  searchVendors,
  getVendorsByCategory,
  type Vendor,
  type CreateVendorInput,
  type UpdateVendorInput,
  type ListVendorsOptions,
} from "./db/company.js";

export { getDatabase, closeDatabase } from "./db/database.js";
