/**
 * microservice-compliance — Compliance management microservice
 */

export {
  createRequirement,
  getRequirement,
  listRequirements,
  updateRequirement,
  deleteRequirement,
  searchRequirements,
  createLicense,
  getLicense,
  listLicenses,
  updateLicense,
  deleteLicense,
  renewLicense,
  listExpiringLicenses,
  getLicenseStats,
  scheduleAudit,
  getAudit,
  listAudits,
  completeAudit,
  getAuditReport,
  deleteAudit,
  getComplianceScore,
  getFrameworkStatus,
  type Requirement,
  type License,
  type Audit,
  type Framework,
  type RequirementStatus,
  type LicenseType,
  type LicenseStatus,
  type AuditStatus,
  type CreateRequirementInput,
  type UpdateRequirementInput,
  type ListRequirementsOptions,
  type CreateLicenseInput,
  type UpdateLicenseInput,
  type ListLicensesOptions,
  type CreateAuditInput,
  type ListAuditsOptions,
} from "./db/compliance.js";

export { getDatabase, closeDatabase } from "./db/database.js";
